### ISSUE TITLE
Improve Favourites feature

### ISSUE THREAD

**Issue by Swarnim01** [Swarnim01/Movie_Listing_Webapp#12]
@arushi2715 great observation. Favourites has repetitive addition issue.

About the theme of the movie app. Try improving it and make it more appealing.
I'll create issues you mentioned here and assign it to you.

_Originally posted by @Swarnim01 in https://github.com/Swarnim01/Movie_Listing_Webapp/issues/10#issuecomment-934092539_

**Comment by arushi2715** [comment]
Sure @Swarnim01!

**Comment by Swarnim01** [comment]
Sure @arushi2715
