### ISSUE TITLE
Improper Navigation

### ISSUE THREAD

**Issue by arun-kushwaha04** [Swarnim01/Movie_Listing_Webapp#20]
@Swarnim01 Currently If I view details of a movie from page three and return back to home I am on the page 1. Ideally I should be directed to page 3.
Possible fix could be using params when we change page like "/home/:pageNumber" so this will ensure proper navigation of the pages.

**Comment by Swarnim01** [comment]
@arun-kushwaha04 . yeah, this could be done.
