### ISSUE TITLE
Refreshing webapp shows invalid screen.

### ISSUE THREAD

**Issue by Swarnim01** [Swarnim01/Movie_Listing_Webapp#3]
When running locally, after logging In to the web app and refreshing the screen, the user still remains in the home screen due the presence of auth token in cookie but after hosting , it shows invalid screen when refreshed. Its possibly due to some wrong server setup. Try to fix it up.

**Comment by gurpreet-legend** [comment]
I want to work on it

**Comment by Swarnim01** [comment]
> I want to work on it

Go ahead @gurpreet-legend

**Comment by gurpreet-legend** [comment]
I have fixed this issue in this PR https://github.com/Swarnim01/Movie_Listing_Webapp/pull/7#issue-747888269 itself, please review

**Comment by gurpreet-legend** [comment]
I have solved this bug in the same PR, should I create a separate PR for this issue?

**Comment by gurpreet-legend** [comment]
Sir, I tried correcting this issue and I guess this is not a token issue, as they are getting saved in the cookies even after hosting. The page is giving 404 on reload because the server does not have such an endpoint, but generally what happens in react-dom is that it automatically re-renders the page whenever such a case is encountered.

**Comment by Swarnim01** [comment]
@gurpreet-legend you got it right till some point . Basically what's happening here is On refresh server was requesting to https://movielistingapp.herokuapp.com/home or /favourites and the backend there was not logic written directly to serve any files so this part was missing - 
if (process.env.NODE_ENV === "production") {
  app.use(express.static("client/build"));
  app.get("/*", (req, res) => {
    res.sendFile(path.resolve(__dirname, "client", "build", "index.html"));
  });
}
here the 3rd line sends index.html where all the frontend logic would be written from start ( like checking cookie -> if present go to home page else login). So now placing this code will not crash the app and send index.html  and all the JS code will get implemented.Also placement of this code on app.js matter. Place it below all routes else no route would be fetched as '/*' will catch everything. For more understanding you can refer to (https://stackoverflow.com/questions/27928372/react-router-urls-dont-work-when-refreshing-or-writing-manually) .

**Comment by Swarnim01** [comment]
I updated it in main branch to test it in deployment so the master branch is update with this issue resolved.If you're finding it difficult to understand feel free to contact on any socials of mine.
I'll close this issue.
