### ISSUE TITLE
Change the left/right arrows feature to pagination feature

### ISSUE THREAD

**Issue by Swarnim01** [Swarnim01/Movie_Listing_Webapp#4]
Since arrows work fine on desktop screens but on mobile screens arrows take too much space and it doesn't look good. Therefore change the arrowhead feature to the pagination feature ( page numbers should appear at the very bottom and should be horizontally centered).

**Comment by harshgupta1249** [comment]
@Swarnim01  I would like to work on this issue.

**Comment by Swarnim01** [comment]
Sure @harshgupta1249 .
