### ISSUE TITLE
Movie details screen

### ISSUE THREAD

**Issue by Swarnim01** [Swarnim01/Movie_Listing_Webapp#5]
Add another screen for the details of the movie (eg. genre , release data , imdb rating , cast etc.) using the moviedb API ( like any typical movie/series screen opens when clicking on it)

**Comment by arun-kushwaha04** [comment]
@Swarnim01 Can I work on this issue ?

**Comment by Swarnim01** [comment]
> @Swarnim01 Can I work on this issue ?

Sure. Go ahead @arun-kushwaha04
