### ISSUE TITLE
Search feature isn't working after hosting.

### ISSUE THREAD

**Issue by Swarnim01** [Swarnim01/Movie_Listing_Webapp#6]
Locally, search features work fine but after hosting the web app it doesn't work due to error :
![image](https://user-images.githubusercontent.com/56025388/135143138-077b734e-12ab-4b64-967d-a0b1ed41a91c.png)
Workaround it and resolve the error.

**Comment by gurpreet-legend** [comment]
I want to work on this

**Comment by Swarnim01** [comment]
> I want to work on this

Go ahead @gurpreet-legend

**Comment by gurpreet-legend** [comment]
Sir, I have set-up the environment as per your instructions but I am still getting this error :
`Proxy error: Could not proxy request /protected from localhost:3000 to http://localhost:5000/.`

**Comment by gurpreet-legend** [comment]
Bug fixed https://github.com/Swarnim01/Movie_Listing_Webapp/pull/7#issue-1013692957, do review it sir

**Comment by Swarnim01** [comment]
@gurpreet-legend make seperate PR for different issues

**Comment by gurpreet-legend** [comment]
I have created a new PR specifically for this issue https://github.com/Swarnim01/Movie_Listing_Webapp/pull/8#issue-1013985949 , please review this sir

**Comment by Swarnim01** [comment]
@gurpreet-legend I've merged it. Great going!
